# №1
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
# №2
# services:
#   web:
#     build: .
#     ports:
#       - 8080:8080
#     volumes:
#       - ./public:/app/public
#       - ./src:/app/src
#       - ./tests:/app/tests
#       - ./package.json:/app/package.json
#       - ./babel.config.js:/app/babel.config.js
